### ISSUE TITLE
Allow for custom *http.Client to be passed to the upper clients

### ISSUE THREAD

**Issue by drgomesp** [letsencrypt-cpanel/cpanelgo#4]
Currently, the *http.Client used for making the API calls are hard-coded inside the client different gateway implementations (e.g.: https://github.com/letsencrypt-cpanel/cpanelgo/blob/eb0532054299c19f6aad2f5445e25ea8ff44bbd2/cpanel/authenticated.go#L115)

I think there should be a way to pass an *http.Client that the user might want to use down to the gateway. An easy approach would be to pass the client into the gateway client constructors:

```go
type JsonApiGateway struct {
	Hostname string
	Username string
	Password string
	Insecure bool
	cl       *http.Client
}

func NewJsonApi(hostname, username, password string, insecure bool, cl *http.Client) (CpanelApi, error) {
	c := &JsonApiGateway{
		Hostname: hostname,
		Username: username,
		Password: password,
		Insecure: insecure,
	}

        if cl != nil {
            c.cl = cl
        }

	return CpanelApi{cpanelgo.NewApi(c)}, nil
}
```

What do you think?

**Comment by alexzorin** [comment]
Agreed, passing a client is a very basic need - in the `whm` package too.

The design of this package is frankly beyond saving, owing to its age. I would be happy to accept your PR, should you want to re-open it.

**Comment by drgomesp** [comment]
@alexzorin reopened. :)

**Comment by alexzorin** [comment]
Thanks!

**Comment by drgomesp** [comment]
@alexzorin should we tag a `v1.1.2` release?

**Comment by alexzorin** [comment]
Good idea, I've pushed a `v1.2.0` tag.
